import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import { createRemoteJWKSet, jwtVerify } from "npm:jose@6.1.0";

const PROJECT="itinerarios-2fa6f",ORIGINS = new Set(["https://itinerarios-2fa6f.web.app","https://itinerarios-2fa6f.firebaseapp.com","http://localhost:5000","http://127.0.0.1:5000",
  "https://jason9891.github.io"
]),JWKS=createRemoteJWKSet(new URL("https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"));
function cors(req:Request){const o=req.headers.get("origin")||"",h:Record<string,string>={vary:"Origin","cache-control":"no-store","access-control-allow-headers":"authorization, content-type","access-control-allow-methods":"POST, OPTIONS"};if(ORIGINS.has(o))h["access-control-allow-origin"]=o;return h}
function json(req:Request,b:any,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...cors(req),"content-type":"application/json; charset=utf-8"}})}
async function secure(req:Request){const origin=req.headers.get("origin")||"";if(!ORIGINS.has(origin))throw Error("Origen no autorizado");const h=req.headers.get("authorization")||"";if(!h.startsWith("Bearer "))throw Error("Falta iniciar sesión");const{payload}=await jwtVerify(h.slice(7),JWKS,{algorithms:["RS256"],issuer:`https://securetoken.google.com/${PROJECT}`,audience:PROJECT});const uid=String(payload.sub||"");if(!uid)throw Error("Identidad Firebase no válida");const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});const{data:u,error}=await db.from("app_usuarios").select("id,email,nombre,rol,itinerarios,activo,firebase_uid").eq("firebase_uid",uid).maybeSingle();if(error)throw error;if(!u||!u.activo||!u.itinerarios?.includes("CEMENTO"))throw Error("Cuenta no autorizada para CEMENTO");return{db,user:u}}
const normOc=(v:unknown)=>String(v??"").replace(/\.0+$/g,"").trim();
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return json(req,{ok:true});if(req.method!=="POST")return json(req,{error:"Método no permitido"},405);try{const{db,user}=await secure(req),b=await req.json().catch(()=>({})),action=String(b.action||"");if(action==="estado"){const{data:last,error}=await db.from("seguimiento_manual_importaciones").select("nombre_archivo,creado_en,usuario,filas_recibidas,abiertas,cerradas,insertadas,actualizadas,movidas").eq("itinerario","CEMENTO").order("id",{ascending:false}).limit(1).maybeSingle();if(error)throw error;return json(req,{ultima_importacion:last||null})}
if(action==="importar_manual"){if(!Array.isArray(b.filas)||!b.filas.length)throw Error("No hay filas manuales para aplicar");if(b.filas.length>5000)throw Error("El archivo supera el máximo de 5000 OCs por importación");const filas=[];for(const raw of b.filas){const oc=normOc(raw?.orden_carga||raw?.payload?.["Orden de Carga"]);if(!oc)continue;const viaje=String(raw?.viaje??raw?.payload?.Viaje??"").trim().toUpperCase();const payload=(raw?.payload&&typeof raw.payload==="object"&&!Array.isArray(raw.payload))?{...raw.payload}:{};payload["Orden de Carga"]=oc;payload.Viaje=viaje;payload["ESTADO OC"]=viaje==="F"?"CERRADO":"ABIERTO";filas.push({orden_carga:oc,viaje,payload})}if(!filas.length)throw Error("No quedaron OCs válidas después de normalizar el archivo");const usuario=String(user.nombre||user.email||user.firebase_uid||"USUARIO");const{data,error}=await db.rpc("cemento_importar_seguimiento_manual",{p_nombre_archivo:String(b.nombre_archivo||"SEGUIMIENTO MANUAL.xlsx"),p_hash_sha256:String(b.hash_sha256||""),p_usuario:usuario,p_filas:filas});if(error)throw error;return json(req,data)}
return json(req,{error:"Acción no encontrada"},404)}catch(e){console.error(e);return json(req,{error:e instanceof Error?e.message:"Error"},400)}});
