import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2.57.4";
import {createRemoteJWKSet,jwtVerify} from "npm:jose@6.1.0";
const PROJECT="itinerarios-2fa6f",ORIGINS=new Set(["https://itinerarios-2fa6f.web.app","https://itinerarios-2fa6f.firebaseapp.com","http://localhost:5000","http://127.0.0.1:5000","https://5000-cs-a2a47bf9-3b6a-4a54-b115-36fc3cb753b5.cs-us-east1-vpcf.cloudshell.dev"]),JWKS=createRemoteJWKSet(new URL("https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"));
function reply(req:Request,body:unknown,status=200){const origin=req.headers.get("origin")||"",h:Record<string,string>={"content-type":"application/json; charset=utf-8","vary":"Origin","access-control-allow-headers":"authorization, content-type","access-control-allow-methods":"GET, OPTIONS"};if(ORIGINS.has(origin))h["access-control-allow-origin"]=origin;return new Response(JSON.stringify(body),{status,headers:h})}
async function secure(req:Request){const origin=req.headers.get("origin")||"";if(!ORIGINS.has(origin))throw new Error("Origen no autorizado");const h=req.headers.get("authorization")||"";if(!h.startsWith("Bearer "))throw new Error("Falta iniciar sesión");const {payload}=await jwtVerify(h.slice(7),JWKS,{algorithms:["RS256"],issuer:`https://securetoken.google.com/${PROJECT}`,audience:PROJECT});const uid=String(payload.sub||"");if(!uid)throw new Error("Identidad Firebase no válida");const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});const {data:u,error}=await db.from("app_usuarios").select("id,email,nombre,rol,itinerarios,activo,firebase_uid").eq("firebase_uid",uid).maybeSingle();if(error)throw error;if(!u||!u.activo||!u.itinerarios?.includes("CEMENTO"))throw new Error("Cuenta no autorizada para CEMENTO");await db.from("app_usuarios").update({ultimo_acceso_en:new Date().toISOString()}).eq("id",u.id);return{db,user:u}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return reply(req,{ok:true});if(req.method!=="GET")return reply(req,{error:"Método no permitido"},405);try{const{db,user}=await secure(req),action=new URL(req.url).pathname.split("/").filter(Boolean).pop();
 if(action==="perfil")return reply(req,{usuario:{nombre:user.nombre,email:user.email,rol:user.rol,itinerarios:user.itinerarios}})
 if(action==="resumen"){const [seg,cfg,sap,lastSap]=await Promise.all([db.from("seguimiento_staging").select("payload").eq("itinerario","CEMENTO").eq("origen","DIARIO"),db.from("cemento_configuracion").select("fecha_inicio_recorrido,actualizado_en").eq("itinerario","CEMENTO").maybeSingle(),db.from("sap_registros_staging").select("id",{count:"exact",head:true}).eq("itinerario","CEMENTO"),db.from("sap_importaciones").select("creado_en").eq("itinerario","CEMENTO").eq("estado","APLICADO").order("creado_en",{ascending:false}).limit(1).maybeSingle()]);for(const x of[seg,cfg,sap,lastSap])if(x.error)throw x.error;const placas=new Set((seg.data||[]).map((x:any)=>String(x.payload?.["Placa Tracto"]||x.payload?.TRACTO||"").trim()).filter(Boolean));return reply(req,{usuario:{nombre:user.nombre,rol:user.rol},unidades:placas.size,ocs_abiertas:seg.data?.length||0,sap_registros:sap.count||0,ultima_actualizacion_sap:lastSap.data?.creado_en||null,rango_gps_desde:cfg.data?.fecha_inicio_recorrido||"—",ultima_actividad:cfg.data?.actualizado_en,precarga:null})}
 if(action==="precarga")return reply(req,{job:null,unidades:[],modo:"CACHE_LOCAL_VIGENTE"})
 if(action==="seguimiento"){const q=await db.from("seguimiento_staging").select("id,orden_carga,payload").eq("itinerario","CEMENTO").eq("origen","DIARIO").order("id",{ascending:false}).limit(250);if(q.error)throw q.error;const registros=(q.data||[]).map((x:any)=>({id:x.id,orden_carga:x.orden_carga,tracto:x.payload?.TRACTO||"",placa:x.payload?.["Placa Tracto"]||"",conductor:x.payload?.CONDUCTOR||"",destino:x.payload?.DESTINO||"",salida_planta:x.payload?.["FECHA DE SALIDA PLANTA YURA/CARACOTO"]||""}));return reply(req,{total:registros.length,registros})}
 if(action==="archivos"){const [s,d,h]=await Promise.all([db.from("sap_registros_staging").select("id",{count:"exact",head:true}).eq("itinerario","CEMENTO"),db.from("seguimiento_staging").select("id",{count:"exact",head:true}).eq("itinerario","CEMENTO").eq("origen","DIARIO"),db.from("seguimiento_staging").select("id",{count:"exact",head:true}).eq("itinerario","CEMENTO").eq("origen","HISTORICO")]);for(const x of[s,d,h])if(x.error)throw x.error;return reply(req,{archivos:[{nombre:"SAP_HISTORICO.xlsx",descripcion:"Órdenes SAP acumuladas y vigentes",registros:s.count||0},{nombre:"SEGUIMIENTO_DIARIO.xlsx",descripcion:"Órdenes abiertas en seguimiento",registros:d.count||0},{nombre:"SEGUIMIENTO_HISTORICO.xlsx",descripcion:"Ciclos cerrados acumulados",registros:h.count||0}]})}
 if(action==="reporte"){const d=await db.from("seguimiento_staging").select("id",{count:"exact",head:true}).eq("itinerario","CEMENTO").eq("origen","DIARIO");if(d.error)throw d.error;return reply(req,{diario:d.count||0,mensaje:"La salida validada de PRUEBA REAL 05 se mantiene congelada hasta migrar y comparar el motor ENVIAR2022."})}
 return reply(req,{error:"Ruta no encontrada"},404)
 }catch(e){return reply(req,{error:e instanceof Error?e.message:"Error de acceso"},401)}});
