import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import { createRemoteJWKSet, jwtVerify } from "npm:jose@6.1.0";

const PROJECT="itinerarios-2fa6f",ORIGINS = new Set(["https://itinerarios-2fa6f.web.app","https://itinerarios-2fa6f.firebaseapp.com","http://localhost:5000","http://127.0.0.1:5000",
  "https://jason9891.github.io"
]),JWKS=createRemoteJWKSet(new URL("https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"));
function cors(req:Request){const o=req.headers.get("origin")||"",h:Record<string,string>={vary:"Origin","cache-control":"no-store","access-control-allow-headers":"authorization, content-type","access-control-allow-methods":"POST, OPTIONS"};if(ORIGINS.has(o))h["access-control-allow-origin"]=o;return h}
function json(req:Request,b:any,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...cors(req),"content-type":"application/json; charset=utf-8"}})}
async function secure(req:Request){const origin=req.headers.get("origin")||"";if(!ORIGINS.has(origin))throw Error("Origen no autorizado");const h=req.headers.get("authorization")||"";if(!h.startsWith("Bearer "))throw Error("Falta iniciar sesión");const{payload}=await jwtVerify(h.slice(7),JWKS,{algorithms:["RS256"],issuer:`https://securetoken.google.com/${PROJECT}`,audience:PROJECT});const uid=String(payload.sub||"");if(!uid)throw Error("Identidad Firebase no válida");const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});const{data:u,error}=await db.from("app_usuarios").select("id,email,rol,itinerarios,activo,firebase_uid").eq("firebase_uid",uid).maybeSingle();if(error)throw error;if(!u||!u.activo||u.rol!=="ADMIN"||!u.itinerarios?.includes("CEMENTO"))throw Error("Se requiere acceso ADMIN a CEMENTO");return{db}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return json(req,{ok:true});if(req.method!=="POST")return json(req,{error:"Método no permitido"},405);try{const{db}=await secure(req),b=await req.json().catch(()=>({})),action=String(b.action||"");if(action!=="cuotas")return json(req,{error:"Acción no encontrada"},404);const{data:cuotas,error}=await db.rpc("itinerarios_cuotas_prueba17");if(error)throw error;return json(req,{cuotas,limites:{database:500*1024*1024,egress:5*1024*1024*1024,storage:1024*1024*1024}})}catch(e){console.error(e);return json(req,{error:e instanceof Error?e.message:"Error"},400)}});
